const fakeData = [
  {
    id: 1,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 2,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 3,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 4,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 5,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 6,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "DSA",
    subtopic: "Arrays",
  },
  {
    id: 7,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 8,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 9,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 10,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 11,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 12,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "DSA",
    subtopic: "LinkedList",
  },
  {
    id: 13,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 14,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 15,
    link: "https://www.youtube.com/embed/qsN1LglrX9s",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 16,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 17,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 18,
    link: "https://www.youtube.com/embed/VB_GWz25B3Q",
    topic: "webd",
    subtopic: "nodejs",
  },
  {
    id: 19,
    link: "https://www.youtube.com/embed/Be69yn3L86A",
    topic: "webd",
    subtopic: "reactjs",
  },
  {
    id: 20,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "webd",
    subtopic: "reactjs",
  },
  {
    id: 21,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "webd",
    subtopic: "reactjs",
  },
  {
    id: 22,
    link: "https://www.youtube.com/embed/Be69yn3L86A",
    topic: "webd",
    subtopic: "reactjs",
  },
  {
    id: 23,
    link: "https://www.youtube.com/embed/Jzfpyo-q-RM",
    topic: "webd",
    subtopic: "reactjs",
  },
  {
    id: 24,
    link: "https://www.youtube.com/embed/Be69yn3L86A",
    topic: "webd",
    subtopic: "reactjs",
  },
];

export default fakeData;
